from constans.error_messages import INVALID_FILE_FORMAT_ERROR, FORMAT_INVALID_PA_PE_ERROR, \
    ID_ADHERENT_CO_ESTAB_IS_NOT_PRESENT_ERROR, ARGUMENT_INPUT_FILE_MANDATORY_ERROR, \
    MIN_LENGTH_ID_ADHERENT_CO_ESTABDHERENT_CO_ETAB_ERROR, ADDITIONAL_PROPERTIES_ERROR
